spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/order_db
    username: ${DB_USER:order_user}
    password: ${DB_PASS:secret}
    driver-class-name: org.postgresql.Driver
  # --- Outbox -> Kafka producer (Spring Cloud Stream) ---
  cloud:
    stream:
      bindings:
        orderPlaced-out-0:
          destination: order-events
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
